In [3]:
import numpy as np
import urllib.request
import matplotlib.pylab as plt
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

# The url with dataset
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits.tra"

raw_data = urllib.request.urlopen(url)
# load the CSV file as a numpy matrix
dataset = np.loadtxt(raw_data, delimiter=",")
# Separating the input attributes from the label
X = dataset[:,0:63]
y = dataset[:,64]

url1 = "http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits.tes"
raw_data1 = urllib.request.urlopen(url1)

datast = np.loadtxt(raw_data1, delimiter=",")
A = datast[:,0:63]
B = datast[:,64]

model = DecisionTreeClassifier()
model.fit(X, y)
print(model)
expected = y
# making predictions to data. Finding the accuracy and confusion matrix.
predicted = model.predict(A)
print(metrics.confusion_matrix(B,predicted))
print("The accuracy is ")
print(metrics.accuracy_score(B, predicted))













DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')
[[172   0   1   0   2   2   0   0   1   0]
 [  0 154   0   7   1   0   2   2   6  10]
 [  1   7 142   5   2   2   2   6   7   3]
 [  0   2  10 144   0   6   0   3   8  10]
 [  1  12   0   0 143   3   7   3   9   3]
 [  1   3   3   4   0 165   5   0   0   1]
 [  0   2   1   0   1   0 173   0   4   0]
 [  0   1   7   0   5  10   0 139  11   6]
 [  0   5   4   3   2   2   0   1 150   7]
 [  0   7   2   4   2   6   0   0   4 155]]
The accuracy is 
0.85531441291
